


































});  console.log(`Server is running on port ${port}`);app.listen(port, () => {// Start the server});  console.log('Connected to MongoDB');db.once('open', () => {db.on('error', console.error.bind(console, 'connection error:'));const db = mongoose.connection;});  useUnifiedTopology: true,  useNewUrlParser: true,mongoose.connect('mongodb://localhost:27017/vitaguidedb', {// Connect to MongoDBapp.use('/api/questionnaire-answers', questionnaireAnswerRoutes);app.use('/api/questionnaires', questionnaireRoutes);// Register routesapp.use(cors());app.use(bodyParser.json());// Middlewareconst questionnaireAnswerRoutes = require('./routes/questionnaireAnswerRoutes');const questionnaireRoutes = require('./routes/questionnaireRoutes');// Import routesconst port = process.env.PORT || 3001;const app = express();const cors = require('cors');const mongoose = require('mongoose');const bodyParser = require('body-parser');const express = require('express');